/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package city_builder;

import org.junit.jupiter.api.Test;

import city_builder.gui.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
