/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package city_builder;

import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;

public class App {

    public static void main(String[] args) {
        
    }
}
